name: Generate Shorts V3


on:

  workflow_dispatch:



jobs:


  models:


    runs-on: ubuntu-latest


    env:

      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}



    steps:


      - name: Checkout repository
        uses: actions/checkout@v4



      - name: Setup Node
        uses: actions/setup-node@v4

        with:

          node-version: 22



      - name: Install dependencies
        run: npm install



      - name: List Gemini Models
        run: npm run models
