name: Generate Shorts V3


on:

  workflow_dispatch:

    inputs:

      topic:

        description: "Video konusu"

        required: true

        default: "arabalar hakkında ilginç bilgiler"


      count:

        description: "Kaç video üretilecek"

        required: true

        default: "3"



jobs:


  generate:


    runs-on: ubuntu-latest


    env:

      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

      PEXELS_API_KEY: ${{ secrets.PEXELS_API_KEY }}

      SHORTS_TOPIC: ${{ inputs.topic }}

      SHORTS_COUNT: ${{ inputs.count }}



    steps:



      - name: Checkout repository

        uses: actions/checkout@v4



      - name: Setup Node

        uses: actions/setup-node@v4

        with:

          node-version: 22



      - name: Setup Python

        uses: actions/setup-python@v5

        with:

          python-version: "3.11"



      - name: Install FFmpeg

        run: |

          sudo apt update

          sudo apt install -y ffmpeg



      - name: Install Node dependencies

        run: |

          npm install



      - name: Install Python AI tools

        run: |

          python -m pip install --upgrade pip

          pip install piper-tts

          pip install openai-whisper

          pip install setuptools

          pip install wheel



      - name: Verify Whisper

        run: |

          python -m whisper --help



      - name: Prepare Piper voice

        run: |

          mkdir -p voices

          python -m piper.download_voices \
            tr_TR-dfki-medium \
            --data-dir voices



      - name: Prepare folders

        run: |

          mkdir -p output/final

          mkdir -p output/work

          mkdir -p output/audio



      - name: Generate Shorts

        run: |

          npm run generate



      - name: Check output

        run: |

          ls -R output



      - name: Upload final videos

        uses: actions/upload-artifact@v4

        with:

          name: shorts-final

          path: output/final/*.mp4

          if-no-files-found: error
